language: python

sudo: false

dist: trusty

python:
 - 2.7

before_install:
 - pip install -r requirements.txt
 - python setup.py install
 - python bootstrap.py
 - ./bin/buildout

script:
 - nosetests -i regulartest -i sphinxtest
